categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'core feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'refactoring'
      - 'maintenance'
template: |
  ## What's Changed

  $CHANGES